import Foundation

/// Represents the classification of documents and images stored in encrypted object storage.
public enum StoredFileCategory: String, Codable, Sendable, CaseIterable, Identifiable {
    /// User documents: prescriptions, medical summaries, clinical notes, research papers.
    case userDocument = "user_document"
    
    /// Bloodwork results, pathology reports, diagnostic lab test panels in PDF format.
    case labPdf = "lab_pdf"
    
    /// Physical vial pictures, lot numbers, box labels, Certificate of Analysis (CoA).
    case vialPhoto = "vial_photo"
    
    /// Body transformation pictures, injection site reactions/healing progress photos.
    case progressPhoto = "progress_photo"
    
    /// Exported clinician summaries, CSV/PDF longitudinal reports generated by Vialr.
    case exportedReport = "exported_report"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .userDocument: return "User Document"
        case .labPdf: return "Lab Test PDF"
        case .vialPhoto: return "Vial Photograph"
        case .progressPhoto: return "Progress Photograph"
        case .exportedReport: return "Exported Clinician Report"
        }
    }

    public var defaultFolderPrefix: String {
        switch self {
        case .userDocument: return "documents"
        case .labPdf: return "lab-pdfs"
        case .vialPhoto: return "vial-photos"
        case .progressPhoto: return "progress-photos"
        case .exportedReport: return "reports"
        }
    }

    public var maxAllowedSizeBytes: Int64 {
        switch self {
        case .userDocument: return 25 * 1024 * 1024 // 25 MB
        case .labPdf: return 50 * 1024 * 1024       // 50 MB
        case .vialPhoto: return 20 * 1024 * 1024     // 20 MB
        case .progressPhoto: return 20 * 1024 * 1024 // 20 MB
        case .exportedReport: return 30 * 1024 * 1024 // 30 MB
        }
    }

    public var allowedContentTypes: Set<String> {
        switch self {
        case .userDocument:
            return ["application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "text/plain", "image/jpeg", "image/png", "image/heic"]
        case .labPdf:
            return ["application/pdf"]
        case .vialPhoto, .progressPhoto:
            return ["image/jpeg", "image/png", "image/heic", "image/webp"]
        case .exportedReport:
            return ["application/pdf", "text/csv", "application/json"]
        }
    }
}

/// Metadata describing the cryptographic protection applied to an object in storage.
public struct StorageEncryptionMetadata: Codable, Sendable, Hashable {
    /// Cryptographic cipher algorithm (e.g. "AES-256-GCM")
    public var algorithm: String
    
    /// Key identifier or KMS alias used for envelope encryption
    public var keyId: String
    
    /// Base64 encoded Initialization Vector (Nonce)
    public var initializationVector: String
    
    /// Base64 encoded Authentication Tag
    public var authenticationTag: String
    
    /// Flag indicating whether the binary payload is ciphertext
    public var isEncrypted: Bool

    public init(
        algorithm: String = "AES-256-GCM",
        keyId: String = "vialr-vault-primary",
        initializationVector: String = "",
        authenticationTag: String = "",
        isEncrypted: Bool = true
    ) {
        self.algorithm = algorithm
        self.keyId = keyId
        self.initializationVector = initializationVector
        self.authenticationTag = authenticationTag
        self.isEncrypted = isEncrypted
    }
}
